-- MySQL Script generated by MySQL Workbench
-- Fri Apr 29 15:23:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolioweb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portfolioweb` ;

-- -----------------------------------------------------
-- Schema portfolioweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolioweb` DEFAULT CHARACTER SET utf8 ;
USE `portfolioweb` ;

-- -----------------------------------------------------
-- Table `portfolioweb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolioweb`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `sobre_mi` VARCHAR(200) NULL,
  `url_foto` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolioweb`.`tipo_empleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolioweb`.`tipo_empleo` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolioweb`.`experiencia_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolioweb`.`experiencia_laboral` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(45) NULL,
  `es_trabajo_actual` TINYINT NOT NULL,
  `fecha_ingreso` DATE NULL,
  `fecha_egreso` DATE NULL,
  `descripcion` VARCHAR(200) NULL,
  `persona_id` INT NOT NULL,
  `tipo_empleo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`, `tipo_empleo_id`),
  CONSTRAINT `fk_experiencia_laboral_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `portfolioweb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiencia_laboral_tipo_empleo1`
    FOREIGN KEY (`tipo_empleo_id`)
    REFERENCES `portfolioweb`.`tipo_empleo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_experiencia_laboral_persona_idx` ON `portfolioweb`.`experiencia_laboral` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_experiencia_laboral_tipo_empleo1_idx` ON `portfolioweb`.`experiencia_laboral` (`tipo_empleo_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `portfolioweb`.`tipo_formacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolioweb`.`tipo_formacion` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolioweb`.`formacion_profesional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolioweb`.`formacion_profesional` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_institucion` VARCHAR(45) NOT NULL,
  `es_estudio_actual` TINYINT NOT NULL,
  `fecha_inicio` DATE NULL,
  `fecha_finalizacion` DATE NULL,
  `persona_id` INT NOT NULL,
  `tipo_formacion_id` INT NOT NULL,
  PRIMARY KEY (`id`, `persona_id`, `tipo_formacion_id`),
  CONSTRAINT `fk_formacion_profesional_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `portfolioweb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formacion_profesional_tipo_formacion1`
    FOREIGN KEY (`tipo_formacion_id`)
    REFERENCES `portfolioweb`.`tipo_formacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_formacion_profesional_persona1_idx` ON `portfolioweb`.`formacion_profesional` (`persona_id` ASC) VISIBLE;

CREATE INDEX `fk_formacion_profesional_tipo_formacion1_idx` ON `portfolioweb`.`formacion_profesional` (`tipo_formacion_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
